import time

from selenium.webdriver.common.keys import Keys

from ipss_automation.base import BasePage
from selenium.webdriver.common.by import By
from ipss_automation.locators import Locators
from ipss_automation.utils import get_otp_value


class PF(BasePage):
    """
    Login common module for all user roles.
    """
    def __init__(self, driver):
        super().__init__(driver)

    def pfesi(self):
        self.click(Locators.DRAWER)
        time.sleep(2)
        self.click(Locators.PAYROLL)
        time.sleep(2)
        self.click(Locators.PF)
        time.sleep(2)
        #self.click(Locators.SELECT_ALL)
        #time.sleep(2)
        #self.click(Locators.UNSELECT_ALL)
        #time.sleep(2)
        self.click(Locators.SORT)
        time.sleep(2)
        self.click(Locators.SORT_PAY)
        time.sleep(2)
        self.click(Locators.SORTE)
        time.sleep(2)
        self.click(Locators.SORT_DOC)
        time.sleep(2)

        self.click(Locators.ROUT)
        time.sleep(2)
        self.driver.switch_to.alert.accept()
        time.sleep(5)
        self.click(Locators.EDII)
        time.sleep(2)
        self.driver.switch_to.alert.accept()
        time.sleep(5)
        self.click(Locators.DELE)
        time.sleep(2)
        self.driver.switch_to.alert.accept()
        time.sleep(5)
        self.click(Locators.SLET)
        self.click((Locators.SLECT))
        time.sleep(2)
        self.click(Locators.ROUT)
        time.sleep(2)
        self.driver.switch_to.alert.accept()
        time.sleep(5)

        self.click(Locators.ADD_INFO)
        time.sleep(2)
        self.click(Locators.PAYY)
        time.sleep(2)
        self.click(Locators.ESI)
        time.sleep(2)
        self.click(Locators.CAN)
        time.sleep(5)

        self.click(Locators.ADD_INFO)
        time.sleep(2)
        self.click(Locators.PAYY)
        time.sleep(2)
        self.click(Locators.ESI)
        time.sleep(2)
        self.click(Locators.SUB)
        time.sleep(5)
        self.click(Locators.SLECT)
        time.sleep(2)
        self.click(Locators.EDII)
        time.sleep(2)
        self.click(Locators.PAYY)
        time.sleep(2)
        self.click(Locators.PAE)
        time.sleep(2)
        self.click(Locators.SUB)
        time.sleep(2)
        self.click(Locators.SLECT)
        time.sleep(2)
        self.click(Locators.ROUT)
        time.sleep(2)
        self.click(Locators.ADD_INFO)
        time.sleep(2)
        self.enter_text(Locators.FROMVALUE, "1200")
        time.sleep(2)
        self.enter_text(Locators.TOVALUE, "1202")
        time.sleep(2)
        self.click(Locators.SUB)
        time.sleep(2)
        self.click(Locators.SLET)
        time.sleep(2)
        self.click(Locators.EDII)
        time.sleep(2)
        self.enter_text(Locators.FROMVALUE, "1204")
        time.sleep(2)
        self.send_keys(Locators.FROMVALUE, Keys.CONTROL + "a")
        self.send_keys(Locators.FROMVALUE, Keys.DELETE)
        self.enter_text(Locators.FROMVALUE, "1204")
        time.sleep(2)
        self.enter_text(Locators.TOVALUE, "1204")
        time.sleep(2)
        self.send_keys(Locators.TOVALUE, Keys.CONTROL + "a")
        self.send_keys(Locators.TOVALUE, Keys.DELETE)
        self.enter_text(Locators.TOVALUE, "1206")
        self.enter_text(Locators.PER, "69")
        self.enter_text(Locators.AMOUN, "900")

        self.click(Locators.SUB)
        time.sleep(2)
        self.click(Locators.SLET)
        time.sleep(2)
        self.click(Locators.DELE)
        time.sleep(2)
        self.driver.switch_to.alert.accept()
        time.sleep(5)
        self.click(Locators.DOWN)
        time.sleep(2)

        self.driver.back()
        time.sleep(2)
