import time
from unittest import TestCase
import unittest
from ipss_automation.base import BasePage
from selenium.webdriver.common.keys import Keys
import HtmlTestRunner
from ipss_automation.locators import Locators


class Transaction(BasePage, unittest.TestCase):

    def __init__(self, driver):
        super().__init__(driver)

    def pay(self):
        self.click(Locators.T_DRAWER)
        time.sleep(3)
        self.click(Locators.T_DROPDOWN)
        time.sleep(3)
        self.click(Locators.T_PAY_TRANSACTION)
        time.sleep(5)
        self.click(Locators.T_ROUTE)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(1)
        self.click(Locators.T_ADD)
        time.sleep(3)
        self.driver.execute_script("window.scrollTo(500,0);")
        time.sleep(2)
        self.click(Locators.T_COMPCODE)
        time.sleep(4)
        self.click(Locators.T_SUBMIT)
        time.sleep(4)
        self.enter_text(Locators.T_COMPCODE, "55677")
        time.sleep(3)
        self.click(Locators.T_COMPANY_NAME)
        time.sleep(4)
        self.enter_text(Locators.T_COMPANY_NAME, "TVS")
        time.sleep(3)
        self.click(Locators.T_FINANCIAL_YEAR)
        time.sleep(4)
        self.enter_text(Locators.T_FINANCIAL_YEAR, "55677")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_CATEGORY)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_CATEGORY, "55677")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_CODE)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_CODE, "6666")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_PERIOD)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_PERIOD, "March 2022")
        time.sleep(3)
        self.click(Locators.T_TOTAL)
        time.sleep(4)
        self.enter_text(Locators.T_TOTAL, "3000.00")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_DESCRIPTION)
        time.sleep(3)
        self.enter_text(Locators.T_PAYMENT_DESCRIPTION, "None")
        time.sleep(3)
        self.click(Locators.T_SUBMIT)
        time.sleep(4)
        self.click(Locators.T_ADD)
        time.sleep(3)
        self.driver.execute_script("window.scrollTo(500,0);")
        time.sleep(2)
        self.click(Locators.T_COMPCODE)
        time.sleep(4)
        self.click(Locators.T_SUBMIT)
        time.sleep(4)
        self.enter_text(Locators.T_COMPCODE, "55677")
        time.sleep(3)
        self.click(Locators.T_COMPANY_NAME)
        time.sleep(4)
        self.enter_text(Locators.T_COMPANY_NAME, "TVS")
        time.sleep(3)
        self.click(Locators.T_FINANCIAL_YEAR)
        time.sleep(4)
        self.enter_text(Locators.T_FINANCIAL_YEAR, "55677")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_CATEGORY)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_CATEGORY, "55677")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_CODE)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_CODE, "6666")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_PERIOD)
        time.sleep(4)
        self.enter_text(Locators.T_PAYMENT_PERIOD, "March 2022")
        time.sleep(3)
        self.click(Locators.T_TOTAL)
        time.sleep(4)
        self.enter_text(Locators.T_TOTAL, "3000.00")
        time.sleep(3)
        self.click(Locators.T_PAYMENT_DESCRIPTION)
        time.sleep(2)
        self.enter_text(Locators.T_PAYMENT_DESCRIPTION, "None")
        time.sleep(3)
        self.click(Locators.T_CANCEL)
        time.sleep(4)
        self.click(Locators.T_ADD)
        time.sleep(4)
        self.click(Locators.T_CANCEL)
        time.sleep(4)
        self.click(Locators.T_EDIT_BUTTON)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(1)
        self.click(Locators.T_SELECT_BOX)
        time.sleep(4)
        self.click(Locators.T_EDIT_BUTTON)
        time.sleep(3)
        self.click(Locators.T_COMPANY_NAME)
        time.sleep(4)
        self.enter_text(Locators.T_COMPCODE, "bb")
        time.sleep(3)
        self.enter_text(Locators.T_FINANCIAL_YEAR, "2000")
        time.sleep(3)
        self.click(Locators.T_SUBMIT)
        time.sleep(3)
        self.click(Locators.T_DES)
        time.sleep(3)
        self.enter_text(Locators.T_DES, "12345")
        time.sleep(3)
        self.send_keys(Locators.T_DES, Keys.ENTER)
        time.sleep(2)
        self.click(Locators.T_SAVE_BUTTON)
        time.sleep(3)
        self.click(Locators.T_SELECT_BOX)
        time.sleep(2)
        self.click(Locators.T_SELECT_BOX1)
        time.sleep(2)
        self.click(Locators.T_ROUTE)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(2)
        self.click(Locators.T_DELETE_BUTTON)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(1)
        self.click(Locators.T_SELECT_BOX)
        time.sleep(8)
        self.click(Locators.T_DELETE_BUTTON)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(1)
        self.click(Locators.T_DOWNLOAD)
        time.sleep(3)
        self.click(Locators.T_SELECT_BOX)
        time.sleep(2)
        self.click(Locators.T_ROUTE)
        time.sleep(3)
        self.click(Locators.T_ADD_PAY)
        time.sleep(3)
        self.click(Locators.T_EMPLOY_NAME)
        time.sleep(3)
        self.enter_text(Locators.T_EMPLOY_NAME, "Bava")
        time.sleep(3)
        self.click(Locators.T_EMPLOY_ID)
        time.sleep(3)
        self.enter_text(Locators.T_EMPLOY_ID, "0001112")
        time.sleep(3)
        self.click(Locators.T_AMOUNT)
        time.sleep(3)
        self.enter_text(Locators.T_AMOUNT, "3000")
        time.sleep(3)
        self.click(Locators.T_NOTE)
        time.sleep(3)
        self.enter_text(Locators.T_NOTE, "NONE")
        time.sleep(3)
        self.click(Locators.T_SUBMIT)
        time.sleep(3)
        self.click(Locators.T_SELECT_BOX3)
        time.sleep(3)
        self.click(Locators.T_EDIT)
        time.sleep(3)
        self.click(Locators.T_EMPLOY_NAME)
        time.sleep(3)
        self.enter_text(Locators.T_EMPLOY_NAME, "II")
        time.sleep(3)
        self.click(Locators.T_SUBMIT)
        time.sleep(3)
        self.click(Locators.T_EMP1)
        time.sleep(3)
        self.enter_text(Locators.T_EMP1, "bava")
        time.sleep(3)
        self.send_keys(Locators.T_EMP1, Keys.ENTER)
        time.sleep(2)
        self.click(Locators.T_SAVE_BUTTON1)
        time.sleep(3)
        self.click(Locators.T_DELETE_DETAIL)
        time.sleep(3)
        self.driver.switch_to.alert.accept()
        time.sleep(3)
        self.click(Locators.T_DOWNLOAD_DETAIL)
        time.sleep(3)
