from selenium.webdriver.common.by import By


class Locators():
    """
    List all element selectors used to test, by this way If any element is changed
    then can change in this (one) file.
    """
    # Login Module
    CSV=(By.XPATH,'//*[@id="csvFileInput"]')
    LOGIN_LINK = (By.XPATH, '//*[@id="responsive-navbar-nav"]/div[2]/a')
    USERNAME_INPUT = (By.ID, 'username')
    PASSWORD_INPUT = (By.XPATH, '//input[@name="password"]')
    LOGIN_SUBMIT_BUTTON = (By.XPATH, '//span[text()="Sign In"]')
    KEEP_BUTTON = (By.XPATH, '//span[text()="Keep me logged in"]')
    SEARCH1 = (By.ID, 'use-autocomplete-demo-option')
    YEAR=(By.ID,"year")
    SEARC= (By.XPATH,'//input[@id="search"]')
    P1 = (By.ID, "use-autocomplete-demo-option-1")
    P2 = (By.ID, "use-autocomplete-demo-option-2")
    P3 = (By.ID, "use-autocomplete-demo-option-3")
    P4 = (By.ID, "use-autocomplete-demo-option-4")
    P5 = (By.ID, "use-autocomplete-demo-option-5")
    P6 = (By.ID, "use-autocomplete-demo-option-6")
    P9 = (By.ID, "use-autocomplete-demo-option-9")
    P8 = (By.ID, "use-autocomplete-demo-option-8")
    P10 = (By.ID, "use-autocomplete-demo-option-10")
    COM=(By.ID,'compcode')

    # Logout Module

    LOGOUT_LINK = (By.CSS_SELECTOR, 'a[class="MuiButtonBase-root MuiIconButton-root co5 MuiIconButton-colorInherit"]')
    # Sequence
    TXT=(By.ID,"tx_view_id")
    IDTY=(By.ID,"fieldname")
    SEQUENCE = (By.ID, 'sequence')
    TEXT_ID = (By.ID, 'tx_view_id')
    PREFIX = (By.ID, 'prefix')
    DESCRIPTION = (By.ID, 'description')
    ZERO_PADDING = (By.ID, 'zeropadding')
    LAST_NO = (By.ID, 'lastno')
    ACTVE = (By.ID, 'activesequence')
    ACTV=(By.ID,"paycatid")
    CLOSE = (By.ID, "cancel")
    CLSE=(By.ID,"close")
    ADDBUTTON = (By.ID, 'addseq')
    EDITBUTTON=(By.ID,"editseq")

    # Sidebar
    DRAWER_ICON = (By.CSS_SELECTOR,
                   'button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"]')

    ROW = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    SROW = (By.CSS_SELECTOR, '.MuiDialog-paper > form:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)')
    SROW1 = (By.CSS_SELECTOR, '..MuiDialog-paper > form:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)')
    ROW3 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(3)')
    ROW9 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(10)')
    ROW1 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(2)')
    ALLR = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable > div:nth-child(2)')
    GENERAL = (By.XPATH, '//span[text()="General"]')
    EMPOLYE = (By.XPATH, '//span[text()="Configure Employee"]')
    DASHBOARD = (By.XPATH, '//span[text()="Dashboard-Report Values"]')
    ATTENDANCE = (By.XPATH, '//span[text()="Attendance"]')
    ATTENDANCE_ENTRY = (By.XPATH, '//span[text()="Attendance Entry"]')
    MANUAL_OT_ENTRY = (By.XPATH, '//span[text()="Over-Time Entry"]')

    # Master Dashboard Report
    ROUTING_BUTTON = (By.ID, 'routing')
    ADD_BUTTON = (By.ID, 'add')
    PTRANS = (By.ID, 'Status')
    DROP = (By.ID, 'Recruitment Status')
    DROP1 = (By.ID, 'Tailors Strength')
    DOCDATE = (By.ID, 'docdate')
    SUBMIT = (By.XPATH, '//span[text()="Submit"]')
    CANCEL = (By.XPATH, '//span[text()="Cancel"]')
    CANCE = (By.XPATH, "/html/body/div[2]/div[3]/div/form/div[2]/button/span[1]")
    CANC=(By.ID,"cancel")
    EDIT_BUTTON = (By.ID, 'edit')
    SUBMI=(By.ID,'submit')
    SAVE_BUTTON = (By.ID, 'save')
    DELETE_BUTTON = (By.ID, 'delete')
    UPLOAD_BUTTON = (By.ID, 'upload')
    DOWNLOAD_BUTTON = (By.ID, 'download')
    # SORT = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(1)')
    SEARCH = (By.CSS_SELECTOR,
              '.MuiDialog-paper > form:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(5)')
    SORT1 = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(2)')
    SORT2 = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(3)')
    COL = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(2)')
    COL3 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(3)')
    COL6 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(6)')
    COL9 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(6)')

    # Dashboard details
    ADD_BUTTON1 = (By.ID, 'add1')
    EDIT_BUTTON1 = (By.ID, 'edit1')
    EDITBUTTON1=(By.ID,'editseq')
    SAVE_BUTTON1 = (By.ID, 'save1')
    DELETE_BUTTON1 = (By.ID, 'delete1')
    UPLOAD_BUTTON1 = (By.ID, 'upload1')
    DOWNLOAD_BUTTON1 = (By.ID, 'download1')
    # Add& editdetails
    COMPANYCOD = (By.ID, 'compcode')
    RVALUE = (By.ID, 'rvalue')
    NOTES = (By.ID, 'notes')
    # Attendance
    # Attendance Entry
    ROUTING_BUTTON_ATT = (By.ID, 'detailpage')
    # add&edit_details
    DOCDATE1 = (By.ID, 'docdate1')
    COMPANY_CODE1 = (By.ID, 'compcode')
    # attendance details
    ID_CARD = (By.ID, 'mui-2')
    IDCARD=(By.ID,'combo-box-demo')
    ARROW = (By.CSS_SELECTOR,
             'button[class()="MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium MuiAutocomplete-popupIndicator css-uge3vf"]')
    PRESENT = (By.ID, 'lop')
    SHIFT = (By.ID, 'shift')
    TEMPLATE = (By.ID, 'temp')
    # Manual Ot
    ID = (By.CSS_SELECTOR,
          'div[class()="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd MuiAutocomplete-inputRoot css-segi59"]')
    OTDATE = (By.ID, 'otdate')
    OTHR = (By.ID, 'othrs')
    DOCDAT = (By.ID, 'docdate')
    # TAB
    T1 = (By.ID, 'scrollable-auto-tab-1')
    T2 = (By.ID, 'scrollable-auto-tab-2')
    T3 = (By.ID, 'scrollable-auto-tab-3')
    T4 = (By.ID, 'scrollable-auto-tab-4')
    T5 = (By.ID, 'scrollable-auto-tab-5')
    T6 = (By.ID, 'scrollable-auto-tab-6')
    T7 = (By.ID, 'scrollable-auto-tab-7')
    T8 = (By.ID, 'scrollable-auto-tab-8')
    T9 = (By.ID, 'scrollable-auto-tab-9')
    T10 = (By.ID, 'scrollable-auto-tab-10')
    IMG = (By.XPATH, '/html/body/div/div/div[2]/div/div/div/div[2]/div/p/div/div[3]/div[2]/input')
    DEL=(By.XPATH,'/html/body/div/div/div[2]/div/div/div/div[2]/div/p/div/div[7]/div/button')
    # DROPDOWN
    # D2=(By.XPATH,"/html/body/div[2]/div[3]/ul/li[8]")
    D11 = (By.XPATH, "/html/body/div[2]/div[3]/ul/li[4]")
    # D1=(By.XPATH,"/html/body/div[2]/div[3]/ul/li[1]")
    D17 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(16)')
    D8 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(8)')
    D1 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(1)')
    D2 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(2)')
    D3 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(3)')
    D4 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(4)')
    D5 = (By.CSS_SELECTOR, 'li.MuiMenuItem-root:nth-child(5)')
    # Edit buttons
    R_SAVE = (By.CSS_SELECTOR, 'button.MuiButton-root:nth-child(4)')
    R_CANCEL = (By.CSS_SELECTOR, 'button.MuiButton-root:nth-child(3)')
    # Empolyee
    DOO = (By.XPATH, '/html/body/div[2]/div[3]/ul/li[13]')
    R_TYPE = (By.ID, 'emptype')
    R_FIRST = (By.ID, 'firstname')
    R_MID = (By.ID, 'middlename')
    R_LAST = (By.ID, 'lastname')
    R_AADHAR = (By.ID, 'aadharname')
    R_DOB = (By.ID, 'dob')
    R_GEN = (By.ID, 'gender')
    R_BLOOD = (By.ID, 'bloodgroup')
    R_NATION = (By.ID, 'nationality')
    R_RELI = (By.ID, 'religion')
    R_FATH = (By.ID, 'fathername')
    R_MOM = (By.ID, 'mothername')
    R_MAR = (By.ID, 'maritalstatus')
    R_SAPOUE = (By.ID, 'spousename')
    R_DOM = (By.ID, 'dateofmarrge')
    R_IDEN = (By.ID, 'identification')
    R_DIS = (By.ID, 'disability')
    R_HE = (By.ID, 'height')
    R_WE = (By.ID, 'weight')
    R_EX = (By.ID, 'exservice')
    R_18 = (By.CSS_SELECTOR,
            'span[class="MuiCheckbox-root MuiCheckbox-colorPrimary MuiButtonBase-root MuiCheckbox-root '
            'MuiCheckbox-colorPrimary PrivateSwitchBase-root css-zun73v"]')
    # Empolyment
    R_DOJ = (By.ID, 'doj')
    R_ADOJ = (By.ID, 'adddoj')
    R_LWD = (By.ID, 'lastworkingday')
    R_DEPDROP = (By.ID, 'deptname')
    R_DEPT = (By.ID, 'dept')
    R_COSTCEN = (By.ID, 'deptccc')
    R_BAND = (By.ID, 'band')
    R_PAY = (By.ID, 'paycat')
    R_PAYTY = (By.ID, 'paytype')
    R_DES = (By.ID, 'design')
    DESGCON = (By.ID, 'desgccc')
    R_ACTIVE = (By.ID, 'active')
    R_PF = (By.ID, 'pf')
    R_ESI = (By.ID, 'ESI')
    R_CONTRAC = (By.ID, 'contractor')
    R_SALARY = (By.ID, 'salary')
    R_SALA_TY = (By.CSS_SELECTOR,
                 'div.MuiToolbar-root:nth-child(5) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > '
                 'div:nth-child(1)')
    R_MON = (By.ID, 'monthly')
    R_OLD = (By.ID, 'oldid')
    R_TEMP = (By.ID, 'tempid')
    R_HOS = (By.ID, 'hostel')
    R_VEHICLE = (By.ID, 'vehicle')
    R_LANG = (By.ID, 'languagesknown')
    # Conatact
    # present Address
    R_ADDR = (By.ID, 'cadd')
    R_TALUK = (By.ID, 'taluk')
    R_PIN = (By.ID, 'pcode')
    R_CONTACT = (By.ID, 'contactno')
    R_DIST = (By.ID, 'district')
    R_TELE = (By.ID, 'telno')
    R_EME = (By.ID, 'emergencyno')
    R_CITY = (By.ID, 'city')
    R_STATE = (By.ID, 'state')
    R_MOBILE = (By.ID, 'mobno')
    R_PERMAIL = (By.ID, 'email')
    R_VILLAGE = (By.ID, 'village')
    R_COUNTRY = (By.ID, 'country1')
    R_CONTACTPER = (By.ID, 'contactperson')
    R_OFFICAL = (By.ID, 'conemail')
    # parmanent Address
    R_PERMANANT = (By.ID, 'mui-p-53479-T-2')
    R_PERMANANT1 = (
        By.CSS_SELECTOR, 'button[class="MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1q2h7u5"]')
    SAME = (By.CLASS_NAME, 'PrivateSwitchBase-input css-1m9pwf3')
    R_ADDR1 = (By.ID, 'cadd1')
    R_TALUK1 = (By.ID, 'taluk1')
    R_PIN1 = (By.ID, 'pcode1')
    R_DIST1 = (By.ID, 'district1')
    R_TELE1 = (By.ID, 'telno1')
    R_CITY1 = (By.ID, 'city1')
    R_STATE1 = (By.ID, 'state1')
    R_MOBILE1 = (By.ID, 'mobno1')
    R_VILLAGE1 = (By.ID, 'village1')
    R_COUNTRY1 = (By.ID, 'country2')
    # Identity
    R_AADHARNO = (By.ID, 'aadharno')
    R_DRIVENO = (By.ID, 'dlno')
    R_PAN = (By.ID, 'panno')
    R_ADOB = (By.ID, 'actualdob')
    R_PASSNO = (By.ID, 'passportno')
    R_ISSUEDATE = (By.ID, 'issuedate')
    R_PLACE = (By.ID, 'placeofissue')
    R_EXPIRY = (By.ID, 'expirydate')
    R_ID = (By.ID, 'idproof')
    R_AGE = (By.ID, 'ageproof')
    R_ADDPROOF = (By.ID, 'addressproof')
    R_REF = (By.ID, 'reference')
    R_ADD1 = (By.ID, 'addproof1')
    R_ADD2 = (By.ID, 'addproof2')
    R_ADD3 = (By.ID, 'addproof3')
    # PF/ESI
    R_PFNO = (By.ID, 'pfno')
    R_UAN = (By.ID, 'uanno')
    R_PFDATE = (By.ID, 'pfdate')
    R_PFREL = (By.ID, 'pfrelievedate')
    R_REASON = (By.ID, 'reason')
    R_ESINO = (By.ID, 'esino')
    R_ESIRELIV = (By.ID, 'esirelievedate')
    R_INSUR = (By.ID, 'insurancename')
    R_INSURNO = (By.ID, 'insuranceno')
    # BankDetails
    R_ADD_BUTTON = (By.CSS_SELECTOR, 'div.tooltip:nth-child(1) > button:nth-child(1) > svg:nth-child(1)')
    R_EDIT_BUTTON = (By.CSS_SELECTOR, 'div.tooltip:nth-child(2) > button:nth-child(1) > svg:nth-child(1)')
    PRADD = (By.CSS_SELECTOR, 'div.tooltip:nth-child(1) > button:nth-child(1)')
    R_SUBMIT = (By.CSS_SELECTOR, 'button.MuiButton-root:nth-child(2)')
    RCANCEL = (By.CSS_SELECTOR, 'button.MuiButton-root:nth-child(1)')
    BACK = (By.ID, 'back-arrow')
    BAC=(By.ID,"back")
    R_DELETE = (By.CSS_SELECTOR, 'div.tooltip:nth-child(2) > button:nth-child(1)')
    R_BANKCODE = (By.ID, 'bcode')
    RBANKCODE = (By.CSS_SELECTOR, 'div.css-1b9dzlr:nth-child(1) > div:nth-child(2) > svg:nth-child(3)')
    R_BNAME = (By.ID, 'bname')
    R_BIFSC = (By.ID, 'bifsc')
    R_BRANCH = (By.ID, 'bbranch')
    R_BTYPE = (By.ID, 'btype')
    R_ACNO = (By.ID, 'acno')
    R_SALAC = (By.ID, 'salacc')
    # EDUCATIONAL DETAILS
    R_COURSE = (By.ID, 'course')
    R_INSISTUTION = (By.ID, 'institution')
    R_YOP = (By.ID, 'yearmonth')
    R_PERCENTAGE = (By.ID, 'percentage')
    # Family details
    RNAME = (By.ID, 'rname')
    RDOB = (By.ID, 'rdob')
    RAGE = (By.ID, 'age')
    RELEATION = (By.ID, 'relationship')
    R_REL = (By.CSS_SELECTOR, '.css-xa1gac > svg:nth-child(3)')
    R_OCCU = (By.ID, 'occupation')
    R_NOMINEE = (By.ID, 'nominee')
    R_PER = (By.ID, 'rper')
    # prevoius employee details
    R_DESG = (By.ID, 'desig')
    R_EXPY = (By.ID, 'expy')
    R_YEAR = (By.ID, 'expym')
    # Traing details
    R_DATE = (By.ID, 'tdate')
    R_TITLE = (By.ID, 'title')
    R_LOCATION = (By.ID, 'tlocation')
    R_DUR = (By.ID, 'duration')
    R_CONDUCT = (By.ID, 'conby')
    REMARK = (By.ID, 'remk')
    # Leave Type
    R_LEAVE = (By.ID, 'ltype')
    R_TLEAVE = (By.ID, 'tleave')
    # Edit employee
    R_FIRSTE = (By.ID, "fname")
    R_AADRESS = (By.ID, 'cadd')

    # Security Buyer Attendance
    DRAWER = (By.CSS_SELECTOR,
              'button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"]')

    ATTENDANECE = (By.XPATH, '//span[text()="Attendance"]')
    SECURITY_BUYER = (By.XPATH, '//span[text()="Security Attendance"]')
    ADD = (By.CSS_SELECTOR, 'svg[data-testid="AddBoxRoundedIcon"]')
    FIN_YEAR = (By.ID, 'finyear')
    COMPANY_CODE = (By.ID, 'compcode')
    DATE = (By.ID, 'docdate')
    SHIF1 = (By.CSS_SELECTOR, 'li[data-value="I"]')
    SEC_TEMP_DES = (By.ID, 'stempdesc')
    SECURITY_TEMPLATE = (By.ID, 'stemp')
    COMMON_TEMPLATE = (By.ID, 'sctemp')
    CB_1 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    EDIT = (By.CSS_SELECTOR, 'svg[data-testid="EditRoundedIcon"]')
    COMMON_TEMPLATE_1 = (By.ID, 'sctemp')
    ARROW = (By.CSS_SELECTOR, 'svg[data-testid="ArrowForwardIcon"]')
    ADD_1 = (By.CSS_SELECTOR, 'svg[data-testid="AddBoxRoundedIcon"]')
    ID_CARD_NO = (By.ID, 'idcardno')
    DATE_1 = (By.ID, 'alndate')
    ATTENDANCE_TIME = (By.CSS_SELECTOR, 'input[name="aintime"]')
    ATTENDANCE_OUTDATE = (By.ID, 'aoutdate')
    ATTENDANCE_OUTTIME = (By.ID, 'aouttime')
    TOTAL_HOURS = (By.ID, 'thrs')
    NOTE = (By.ID, 'note')
    HOURS_2 = (By.ID, 'thrs')
    CELL_EDIT = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(2)')
    SAVE = (By.CSS_SELECTOR, 'svg[data-testid="SaveRoundedIcon"]')
    CMPY_CODE = (By.XPATH, '//span[text()="Company Code"]')
    FIN_YEAR1 = (By.XPATH, '//span[text()="Financial Year"]')
    DOC_YEAR = (By.XPATH, '//span[text()="Document Date"]')
    SHIFT1 = (By.ID, 'shift')
    SEC_TEMP = (By.XPATH, '//span[text()="Sec Temp Des"]')
    SEC_TEMPLATE = (By.XPATH, '//span[text()="Security Template"]')
    COM_TEMP = (By.XPATH, '//span[text()="Common Template"]')
    # Master table
    CELL1 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(2)')
    CELL2 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(5)')
    CELL3 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(2)')
    CELL4 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(3)')
    CELL5 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(3)')

    # BANKING MASTER
    MAS_DATA = (By.XPATH, '//span[text()="Master Data"]')
    BANK = (By.XPATH, '//span[text()="Bank Entry"]')
    ADD1 = (By.ID, 'add')
    ADD_BANK = (By.CSS_SELECTOR, 'svg[data-testid="AddBoxRoundedIcon"]')
    COMCODE = (By.ID, 'compcode')
    COMPNAME = (By.ID, 'compname')
    BCODE = (By.ID, 'bcode')
    BNAME = (By.ID, 'bname')
    BADD = (By.ID, 'badd')
    BIFSC = (By.ID, 'bifsc')
    BBRANCH = (By.ID, 'bbranch')
    ACTIVE = (By.ID, 'active')
    TRUE = (By.CSS_SELECTOR, 'li[data-value="T"]')
    FALSE = (By.CSS_SELECTOR, 'li[data-value="F"]')
    SUBMIT2 = (By.ID, 'submit')
    DELETE = (By.ID, 'delete')
    EDIT_CELL = (By.CSS_SELECTOR,
                 'div[class="ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-column-hover ag-cell-focus ag-cell-value"]')
    TRUE1 = (By.CSS_SELECTOR,
             'div[class="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd MuiAutocomplete-inputRoot css-segi59"] input[value="T"]')
    FALSE1 = (By.LINK_TEXT,
              'div[class="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedEnd MuiAutocomplete-inputRoot css-segi59"] input[value="F"]')

    # INDIVIDUAL PAY FOR MASTER DATA

    INDIVIDUAL = (By.XPATH, '//span[text()="Individual Pay"]')
    PAYCODE = (By.ID, 'paycode')
    PAYDES = (By.ID, 'paydesc')
    PAYAMOUNT = (By.ID, 'preamount')
    INCAMOUNT = (By.ID, 'incamount')
    AMOUNT = (By.ID, 'amount')
    DOWNLOAD = (By.CSS_SELECTOR, 'svg[data-testid="DownloadRoundedIcon"]')
    CANCEL1 = (By.XPATH, '//span[text()="Cancel"]')
    E1 = (By.CSS_SELECTOR,
          'div[class="ag-row-even ag-row ag-row-level-0 ag-row-position-absolute ag-row-first ag-row-focus"] div[class="ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-cell-focus ag-cell-value"]')
    # pay transaction master
    T_DRAWER = (By.CSS_SELECTOR,
                'button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"]')
    T_DROPDOWN = (By.XPATH, '//span[text()="Master Data"]')
    T_PAY_TRANSACTION = (By.XPATH, '//span[text()="Pay Transactions"]')
    T_SORTING = (By.XPATH, '//span[text()="Master Id"]')
    T_MENU = (By.CSS_SELECTOR, 'span[class="ag-header-icon ag-header-cell-menu-button"]')
    T_ADD = (By.ID, 'add')
    T_COMPCODE = (By.ID, 'compcode')
    T_COMPANY_NAME = (By.ID, 'compname')
    T_FINANCIAL_YEAR = (By.ID, 'finyear')
    T_PAYMENT_CATEGORY = (By.ID, 'paycat')
    T_PAYMENT_PERIOD = (By.ID, 'payperiod')
    T_PAYMENT_CODE = (By.ID, 'paycode')
    T_PAYMENT_DESCRIPTION = (By.ID, 'paydesc')
    T_TOTAL = (By.ID, 'totamt')
    T_SUBMIT = (By.XPATH, '//span[text()="Submit"]')
    T_CANCEL = (By.XPATH, '//span[text()="Cancel"]')
    T_EDIT_BUTTON = (By.ID, 'edit')
    T_SELECT_BOX = (By.CSS_SELECTOR, '.ag-center-cols-container  > div:nth-child(3)')
    T_SELECT_BOX1 = (By.CSS_SELECTOR, '.ag-center-cols-container  > div:nth-child(2)')
    T_SELECT_BOX3 = (By.CSS_SELECTOR, '.ag-center-cols-container  > div:nth-child(1)')
    T_ROUTE = (By.ID, 'route')
    T_DELETE_BUTTON = (By.ID, 'delete')
    T_DOWNLOAD = (By.ID, 'download')
    T_DES = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(3)')
    T_SAVE_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[2]/div/div/div/div[1]/header/div/div[2]/div[4]/button')
    # VEchile

    E_VECHILE_ID = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(1)')
    E_ADD_PAY = (By.ID, 'adddetail')
    E_EMPLOY_ID = (By.ID, 'empid1')
    E_EMPLOY_NAME = (By.ID, 'enameidno')
    E_AMOUNT = (By.ID, 'amount')
    E_NOTE = (By.ID, 'note')
    E_MASTER_ID = (By.ID, 'hrmpaydetailid')
    E_EDIT = (By.ID, 'editdetail')
    E_AMOUNT_TYPE = (By.ID, 'ag-509-input')
    E_DOWNLOAD = (By.ID, 'download')
    E_VECHILE_PAGE = (By.XPATH, '//span[text()="Vehicle Entry"]')
    E_DOC_DATE = (By.ID, 'docdate')
    E_VECHILE_NO = (By.ID, 'vehicleno')
    E_VECHILE_NAME = (By.ID, 'vehiclename')
    E_VECHILE_TYPE = (By.ID, 'vehicletype')
    E_THREE_WHEELER = (By.CSS_SELECTOR, '#three')
    E_VECHILE_CATEGORY = (By.ID, 'vehiclecatgory')
    E_OTHERS = (By.ID, 'othr')
    E_TRAVEL_NAME = (By.ID, 'travelsname')
    E_ROUTE_NO = (By.ID, 'rootno')
    E_THREE = (
        By.CSS_SELECTOR, 'li[class="MuiMenuItem-root MuiMenuItem-gutters Mui-selected MuiButtonBase-root css-1km1ehz"]')
    E_OWNER_NAME = (By.ID, 'ownername')
    E_DRIVER_NAME = (By.ID, 'drivername')
    E_VECHILE_ROOT = (By.ID, 'vehicleroot')
    E_TARGET = (By.ID, 'target')
    E_KM = (By.ID, 'km')
    E_RENT = (By.ID, 'vrent')
    E_ACTIVE_BOX = (By.CSS_SELECTOR, 'input[class="PrivateSwitchBase-input css-1m9pwf3"]')
    E_DELETE_BUTTON = (By.ID, 'delete')
    E_SAVE_BUTTON = (By.XPATH, '//*[@id="root"]/div/div[2]/div/div/div/div[1]/header/div/div[2]/div[4]/button')
    E_DELETE_DETAIL = (By.ID, 'deletedet')
    E_EMP1 = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(1)')
    E_DOWNLOAD_DETAIL = (By.ID, 'downloaddet')
    E_SAVE_BUTTON1 = (By.XPATH, '//*[@id="root"]/div/div[2]/div/div/div/div[1]/header/div/div[2]/div[3]/button')
    E_SAVE = (By.CSS_SELECTOR, 'span[class="MuiButton-label"]')
    E_SAVE_BUTTON2 = (By.ID, 'save')
    # < ----Village ---->
    V_DRAWER = (By.CSS_SELECTOR,
                'button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"]')
    V_MASTER_DATA = (By.XPATH, "//span[text()='Master Data']")
    V_VILLAGE = (By.XPATH, "//span[text()='Village']")
    V_CHECK_BOX = (By.ID, 'ag-47-input')
    V_SELECT_BOX = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    V_SELECT_BOX1 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(2)')
    V_ADD = (By.ID, 'add')
    V_VILLAGE_NAME = (By.ID, 'villagename')
    V_DROP_DOWN = (By.ID, 'active')
    V_CHOOSE_DROP = (By.ID, 'true')
    V_SUBMIT_BUTTON = (By.ID, 'submit')
    V_EDIT_BUTTON = (By.ID, 'edit')
    V_CANCEL_BUTTON = (By.ID, 'cancel')
    V_DELETE_BUTTON = (By.ID, 'delete')
    V_UPLOAD_BUTTON = (By.ID, 'upload')
    V_EXPORT_BUTTON = (By.ID, 'download')
    V_BOX_BUTTON = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(2)')
    V_SAVE_BUTTON = (By.ID, 'save')
    # Payroll master
    P_DRAWER = (By.CSS_SELECTOR,
                'button[class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit MuiIconButton-edgeStart"]')
    P_PAYROLL_MASTER = (By.XPATH, "//span[text()='Payroll Master']")
    P_PAY_STRUCTURE = (By.XPATH, "//span[text()='Pay Structure']")
    P_ADD = (By.ID, 'add')
    P_COMPANY_CODE = (By.ID, 'compcode')
    P_DOCUMENT_DATE = (By.ID, 'docdate')
    P_FINANCIAL_YEAR = (By.ID, 'finyear')
    P_PAYMENT_CATEGORY = (By.ID, 'paycat')
    P_TYPE_BUTTON = (By.ID, 'utype')
    P_SUBMIT_BUTTON = (By.ID, 'submit')
    P_CANCEL_BUTTON = (By.ID, 'cancel')
    P_SELECT_BOX = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    P_EDIT_BUTTON = (By.ID, 'edit')
    P_BOX_BUTTON = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(5)')
    P_SAVE_BUTTON = (By.ID, 'save')
    P_DELETE_BUTTON = (By.ID, 'delete')
    P_BUTTON = (By.ID, 'upload')
    P_DOWNLOAD_BUTTON = (By.ID, 'masterdownload')
    P_SELECT_BOX1 = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(2)')
    P_ROUTE = (By.ID, 'route')
    P_ADD_BUTTON = (By.ID, 'adddetail')
    P_PAY_CODE = (By.ID, 'paycode')
    P_EARNED_CODE = (By.ID, 'epaycode')
    P_PAY_DESCRIPTION = (By.ID, 'paydesc')
    P_PICK_FORM = (By.ID, 'pickfrom')
    P_FORMULA = (By.ID, 'formula')
    P_NOTES = (By.ID, 'notes')
    P_DOWNLOAD_BUTTON1 = (By.ID, 'download')

    # Payrollmaster

    PAYROLL = (By.XPATH, "//span[text()='Payroll Master']")
    PF = (By.XPATH, "//a[@href='/pfesi']")
    # SELECT_ALL = (By.XPATH, "//input[@id='ag-147-input']")
    # UNSELECT_ALL = (By.XPATH, "//input[@id='ag-147-input']")
    SORT = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(1)')
    SORT_PAY = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(1)')
    SORTE = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(2)')
    SORT_DOC = (By.CSS_SELECTOR, 'div.ag-header-cell-sortable:nth-child(2)')
    # FLOATING_FILTER = (By.XPATH, "//span[@class='ag-icon ag-icon-menu']")
    # FLOATD = (By.XPATH, "//input[@id='ag-9-input']")
    # FLOTP = (By.XPATH, "//input[@id='ag-11-input']")
    # SELECT_IA = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    # MASTER_PAGE = (By.XPATH,"//button[@id='pf/esi']")
    ROUT = (By.XPATH, "//button[@id='pf/esi']")
    ADD_INFO = (By.XPATH, "//button[@id='add']")
    CAN = (By.ID, "cancel")
    PAYY = (By.XPATH, "//div[@id='paycode']")
    ESI = (By.CSS_SELECTOR, "li[data-value='ESI']")
    SUB = (By.ID, "submit")
    SLET = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    SLECT = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(2)')
    EDII = (By.ID, "edit")
    PER = (By.ID, "per")
    AMOUN = (By.ID, "amount")

    PAE = (By.CSS_SELECTOR, "li[data-value='PF']")
    FROMVALUE = (By.ID, "fromvalue")
    TOVALUE = (By.ID, "tovalue")
    DELE = (By.ID, "delete")
    DOWN = (By.ID, "download")

    # production incentive
    DRAW = (By.XPATH, "//button[@aria-label='open drawer']")
    PAY = (By.XPATH, "//span[text()='Payroll Master']")
    PRODUCTIVE = (By.XPATH, "//a[@href='/prodincentive']")
    CODE = (By.ID, "compcode")
    CNA = (By.ID, "compname")
    FYE = (By.ID, "finyear")
    PCAT = (By.ID, "paycat")
    PCO = (By.ID, "paycode")
    PPE = (By.ID, "payperiod")
    PDES = (By.ID, "paydesc")
    TOT = (By.ID, "totamt")
    ROUTE = (By.ID, "route")
    SUB1 = (By.ID, "submit")
    CAN1 = (By.XPATH, '//span[text()="Cancel"]')
    SELECT = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    EDII1 = (By.ID, "edit")
    DELE1 = (By.ID, "delete")
    DELE2 = (By.ID, "deletedet")
    DOWN1 = (By.ID, "download")
    DOWN2 = (By.ID, "downloaddet")

    CELL = (By.CSS_SELECTOR, 'div.ag-cell:nth-child(3)')
    SELEC = (By.CSS_SELECTOR, '.ag-center-cols-container > div:nth-child(1)')
    SUB2 = (By.XPATH, "//span[text()='Submit']")
    ADDTE = (By.ID, "adddetail")
    EMPNAME = (By.ID, "enameidno")
    EMPID = (By.ID, "empid1")
    AMP = (By.ID, "amount")
    NOT = (By.ID, "note")
    DAT = (By.ID, "incentive")
    # onduty
    ON_DUTY = (By.XPATH, '//span[text()="On-Duty Entry"]')
    DETAIL = (By.ID, 'detailpage')
    FIN = (By.XPATH, '//*[@id="combo-box-demo"]')
    ID = (By.XPATH, '//*[@id="combo-box-demo"]')
    ATTENDANCE_T = (By.XPATH, '//span[text()="Attendance"]')
    EMPN = (By.ID, 'empname')
    OD = (By.ID, 'oday')
    OHD = (By.ID, 'ohday')
    HRS = (By.ID, 'thrs')
    T_COMP = (By.XPATH, '/html[1]/body[1]/div[2]/div[3]/div[1]/form[1]/div[2]/p[1]/div[2]/div[1]/div[1]/input[1]')
    CN = (By.XPATH, '//body/div[2]/div[3]/div[1]/form[1]/div[2]/p[1]/div[3]/div[1]/div[1]/input[1]')
    P_CAT = (By.CSS_SELECTOR, 'div.css-1l6di18:nth-child(5) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)')
    E_DO_DATE = (By.ID, 'odate')
    MASTER_DATA = (By.XPATH, '//span[text()="Master Data"]')
